import matplotlib.pyplot as plt
import numpy as np


datas1=np.loadtxt("TDOS.dat",dtype=np.float64,skiprows=1) 
datas2=np.loadtxt("PDOS_USER.dat",dtype=np.float64,skiprows=1) 

f = plt.figure()
f.set_figwidth(10)
f.set_figheight(8)

plt.fill_between(datas1[:,0], datas1[:,1], label="up TDOS", color='black',alpha=0.2)
plt.plot(datas1[:,0], datas1[:,1], linewidth=1, color='black', alpha=0.5)
plt.fill_between(datas1[:,0], datas1[:,2], label="down TDOS", color='black', linestyle='--', alpha=0.2)
plt.plot(datas1[:,0], datas1[:,2], linewidth=1, color='black', linestyle='--', alpha=0.5)
plt.fill_between(datas2[:,0], datas2[:,1], label='up In all', color='purple', alpha=0.3)
plt.plot(datas2[:,0], datas2[:,1], linewidth=1, color='purple', alpha=0.5)
plt.fill_between(datas2[:,0], datas2[:,2], label='up In all', color='purple', alpha=0.2, linestyle='--')
plt.plot(datas2[:,0], datas2[:,2], linewidth=1, color='purple', alpha=0.5, linestyle='--')
plt.fill_between(datas2[:,0], datas2[:,3], label='up Fe all', color='cornflowerblue', alpha=0.3)
plt.plot(datas2[:,0], datas2[:,3], linewidth=1, color='cornflowerblue', alpha=0.5)
plt.fill_between(datas2[:,0], datas2[:,4], label='up In all', color='cornflowerblue', alpha=0.2, linestyle='--')
plt.plot(datas2[:,0], datas2[:,4], linewidth=1, color='cornflowerblue', alpha=0.5, linestyle='--')
plt.fill_between(datas2[:,0], datas2[:,5], label='up In all', color='orange', alpha=0.3)
plt.plot(datas2[:,0], datas2[:,5], linewidth=1, color='orange', alpha=0.5)
plt.fill_between(datas2[:,0], datas2[:,6], label='up In all', color='orange', alpha=0.2, linestyle='--')
plt.plot(datas2[:,0], datas2[:,6], linewidth=1, color='orange', alpha=0.5, linestyle='--')
plt.legend()
plt.title("Density of States", fontsize=40)
plt.xlabel("Energy (ev)", fontsize=20)
plt.ylabel("states/eV", fontsize=20)
plt.show()

f = plt.figure()
f.set_figwidth(10)
f.set_figheight(8)

plt.fill_between(datas1[:,0], datas1[:,1], label="up TDOS", color='black',alpha=0.2)
plt.plot(datas1[:,0], datas1[:,1], linewidth=1, color='black', alpha=0.5)
plt.fill_between(datas1[:,0], datas1[:,2], label="down TDOS", color='black', linestyle='--', alpha=0.2)
plt.plot(datas1[:,0], datas1[:,2], linewidth=1, color='black', linestyle='--', alpha=0.5)
plt.fill_between(datas2[:,0], datas2[:,1], label='up In all', color='purple', alpha=0.3)
plt.plot(datas2[:,0], datas2[:,1], linewidth=1, color='purple', alpha=0.5)
plt.fill_between(datas2[:,0], datas2[:,2], label='up In all', color='purple', alpha=0.2, linestyle='--')
plt.plot(datas2[:,0], datas2[:,2], linewidth=1, color='purple', alpha=0.5, linestyle='--')
plt.fill_between(datas2[:,0], datas2[:,3], label='up Fe all', color='cornflowerblue', alpha=0.3)
plt.plot(datas2[:,0], datas2[:,3], linewidth=1, color='cornflowerblue', alpha=0.5)
plt.fill_between(datas2[:,0], datas2[:,4], label='up In all', color='cornflowerblue', alpha=0.2, linestyle='--')
plt.plot(datas2[:,0], datas2[:,4], linewidth=1, color='cornflowerblue', alpha=0.5, linestyle='--')
plt.fill_between(datas2[:,0], datas2[:,5], label='up In all', color='orange', alpha=0.3)
plt.plot(datas2[:,0], datas2[:,5], linewidth=1, color='orange', alpha=0.5)
plt.fill_between(datas2[:,0], datas2[:,6], label='up In all', color='orange', alpha=0.2, linestyle='--')
plt.plot(datas2[:,0], datas2[:,6], linewidth=1, color='orange', alpha=0.5, linestyle='--')
plt.legend()
plt.title("Density of States", fontsize=40)
plt.xlabel("Energy (ev)", fontsize=20)
plt.ylabel("states/eV", fontsize=20)
plt.savefig("testdos.svg")