import matplotlib.pyplot as plt
import numpy as np


datas=np.loadtxt("ABSORPTION.dat",dtype=np.float64,skiprows=1) 

fig, axs = plt.subplots(3,2,figsize=(10,8))
axs[0,0].plot(datas[:,0], datas[:,1], label='xx', color='orange')
axs[0,0].legend()
axs[0,1].plot(datas[:,0], datas[:,2], label='yy', color='blue')
axs[0,1].legend()
axs[1,0].plot(datas[:,0], datas[:,3], label='zz', color='red')
axs[1,0].legend()
axs[1,1].plot(datas[:,0], datas[:,4], label='xy', color='green')
axs[1,1].legend()
axs[2,0].plot(datas[:,0], datas[:,5], label='yz', color='black')
axs[2,0].legend()
axs[2,1].plot(datas[:,0], datas[:,6], label='zx', color='violet')
axs[2,1].legend()
fig.suptitle('Absorption', fontsize=20)
fig.supylabel('cm^-1')
fig.supxlabel('Energy (eV)')
fig.tight_layout()
plt.show()

fig, axs = plt.subplots(3,2,figsize=(10,8))
axs[0,0].plot(datas[:,0], datas[:,1], label='xx', color='orange')
axs[0,0].legend()
axs[0,1].plot(datas[:,0], datas[:,2], label='yy', color='blue')
axs[0,1].legend()
axs[1,0].plot(datas[:,0], datas[:,3], label='zz', color='red')
axs[1,0].legend()
axs[1,1].plot(datas[:,0], datas[:,4], label='xy', color='green')
axs[1,1].legend()
axs[2,0].plot(datas[:,0], datas[:,5], label='yz', color='black')
axs[2,0].legend()
axs[2,1].plot(datas[:,0], datas[:,6], label='zx', color='violet')
axs[2,1].legend()
fig.suptitle('Absorption', fontsize=20)
fig.supylabel('cm^-1')
fig.supxlabel('Energy (eV)')
fig.tight_layout()
plt.savefig("test.svg")
