import matplotlib.pyplot as plt
import numpy as np
import matplotlib


datas1=np.loadtxt("TDOS.dat",dtype=np.float64,skiprows=1) 
datas2=np.loadtxt("PDOS_USER.dat",dtype=np.float64,skiprows=1)

fig, axs=plt.subplots(4, sharex='col', sharey='row', figsize=(10,8))

axs[0].plot(datas1[:,0], datas1[:,1], label="up TDOS", color='darkgreen', linewidth=1)
axs[0].axhline(0, c='black', alpha=0.3, linestyle='--')
axs[0].plot(datas1[:,0], datas1[:,2], label="down TDOS", color='darkgreen', linewidth=1)
axs[1].plot(datas2[:,0], datas2[:,1], label='up In all', color='purple', linewidth=1)
axs[1].axhline(0, c='black', alpha=0.3, linestyle='--')
axs[1].plot(datas2[:,0], datas2[:,2], label='up In all', color='purple', linewidth=1)
axs[2].plot(datas2[:,0], datas2[:,3], label='up Fe all', color='cornflowerblue', linewidth=1)
axs[2].axhline(0, c='black', alpha=0.3, linestyle='--')
axs[2].plot(datas2[:,0], datas2[:,4], label='up Fe all', color='cornflowerblue', linewidth=1)
axs[3].plot(datas2[:,0], datas2[:,5], label='up O all', color='orange', linewidth=1)
axs[3].plot(datas2[:,0], datas2[:,6], label='up O all', color='orange', linewidth=1)
axs[3].axhline(0, c='black', alpha=0.3, linestyle='--')
axs[0].legend()
axs[1].legend()
axs[2].legend()
axs[3].legend()
fig.suptitle("Density of States", fontsize=40)
fig.supxlabel("Energy (ev)", fontsize=20)
fig.supylabel("arbitrary", fontsize=20)
fig.tight_layout()
plt.subplots_adjust(hspace=.0)
plt.show()

fig, axs=plt.subplots(4, sharex='col', sharey='row', figsize=(10,8))

axs[0].plot(datas1[:,0], datas1[:,1], label="up TDOS", color='darkgreen', linewidth=1)
axs[0].axhline(0, c='black', alpha=0.3, linestyle='--')
axs[0].plot(datas1[:,0], datas1[:,2], label="down TDOS", color='darkgreen', linewidth=1)
axs[1].plot(datas2[:,0], datas2[:,1], label='up In all', color='purple', linewidth=1)
axs[1].axhline(0, c='black', alpha=0.3, linestyle='--')
axs[1].plot(datas2[:,0], datas2[:,2], label='up In all', color='purple', linewidth=1)
axs[2].plot(datas2[:,0], datas2[:,3], label='up Fe all', color='cornflowerblue', linewidth=1)
axs[2].axhline(0, c='black', alpha=0.3, linestyle='--')
axs[2].plot(datas2[:,0], datas2[:,4], label='up Fe all', color='cornflowerblue', linewidth=1)
axs[3].plot(datas2[:,0], datas2[:,5], label='up O all', color='orange', linewidth=1)
axs[3].plot(datas2[:,0], datas2[:,6], label='up O all', color='orange', linewidth=1)
axs[3].axhline(0, c='black', alpha=0.3, linestyle='--')
axs[0].legend()
axs[1].legend()
axs[2].legend()
axs[3].legend()
fig.suptitle("Density of States", fontsize=40)
fig.supxlabel("Energy (ev)", fontsize=20)
fig.supylabel("arbitrary", fontsize=20)
fig.tight_layout()
plt.subplots_adjust(hspace=.0)
plt.savefig("testdos.svg")