import matplotlib.pyplot as plt
import numpy as np
import matplotlib


datas1=np.loadtxt("TDOSCo.dat",dtype=np.float64,skiprows=1) 
datas2=np.loadtxt("PDOS_USERCo.dat",dtype=np.float64,skiprows=1)

f = plt.figure()
f.set_figwidth(10)
f.set_figheight(8)
plt.plot(datas1[:,0], datas1[:,1], label="InCoO3", color='darkgreen', linewidth=2, ls='-')
plt.plot(datas1[:,0], datas1[:,2], color='darkgreen', linewidth=2,ls='-')
plt.plot(datas2[:,0], datas2[:,1], label='In', color='purple', linewidth=2,ls='-.')
plt.plot(datas2[:,0], datas2[:,2], color='purple', linewidth=2,ls='-.')
plt.plot(datas2[:,0], datas2[:,3], label='Co', color='cornflowerblue', linewidth=2,ls='--')
plt.plot(datas2[:,0], datas2[:,4], color='cornflowerblue', linewidth=2,ls='--')
plt.plot(datas2[:,0], datas2[:,5], label='O', color='orange', linewidth=2,ls=':')
plt.plot(datas2[:,0], datas2[:,6], color='orange', linewidth=2,ls=":")
plt.ylim([-20,20])
plt.xlim([-20,10])
plt.axhline(0, c='black', alpha=0.3, linestyle='-')
plt.axvline(0, c='black', alpha=0.3, linestyle='-.')
plt.legend()
#plt.title("InFeO3", fontsize=40)
plt.xlabel("Energy (ev)", fontsize=20)
plt.ylabel("Density of States (arbitrary)", fontsize=20)
plt.show()

f = plt.figure()
f.set_figwidth(10)
f.set_figheight(8)
plt.plot(datas1[:,0], datas1[:,1], label="InCoO3", color='darkgreen', linewidth=2, ls='-')
plt.plot(datas1[:,0], datas1[:,2], color='darkgreen', linewidth=2,ls='-')
plt.plot(datas2[:,0], datas2[:,1], label='In', color='purple', linewidth=2,ls='-.')
plt.plot(datas2[:,0], datas2[:,2], color='purple', linewidth=2,ls='-.')
plt.plot(datas2[:,0], datas2[:,3], label='Co', color='cornflowerblue', linewidth=2,ls='--')
plt.plot(datas2[:,0], datas2[:,4], color='cornflowerblue', linewidth=2,ls='--')
plt.plot(datas2[:,0], datas2[:,5], label='O', color='orange', linewidth=2,ls=':')
plt.plot(datas2[:,0], datas2[:,6], color='orange', linewidth=2,ls=":")
plt.ylim([-20,20])
plt.xlim([-20,10])
plt.axhline(0, c='black', alpha=0.3, linestyle='-')
plt.axvline(0, c='black', alpha=0.3, linestyle='-.')
plt.legend()
#plt.title("InFeO3", fontsize=40)
plt.xlabel("Energy (ev)", fontsize=20)
plt.ylabel("Density of States (arbitrary)", fontsize=20)
plt.savefig("DosInCoO3.png")